version: "3.7"
services:
  service-discovery:
    build:
      context: ../service-discovery/
      dockerfile: Dockerfile
    container_name: service-discovery
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PORT=8761
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    networks:
      - pal-network
    
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - pal-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    
  user-service:
    build:
      context: ../user/
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - pal-network
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/

  transaction-service:
    build:
      context: ../transaction/
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      transactiondb:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://transactiondb:3306/transaction?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_RABBITMQ_HOST=rabbitmq
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    networks:
      - transaction-network
      - pal-network

  transactiondb:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=transaction
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - transaction-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - 8080:8080
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    depends_on:
      service-discovery:
        condition: service_healthy
      user-service:
        condition: service_started
      transaction-service:
        condition: service_started
    networks:
      - pal-network

volumes:
  mysql-data:

networks:
  transaction-network:
    name: transaction-network
  pal-network:
    name: pal-network
    driver: bridge
