version: "3.7"
services:
  service-discovery:
    image: lucagrandi/portfolio-pal:service-discovery
    container_name: service-discovery
    ports:
      - 8761:8761
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PORT=8761
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    networks:
      - pal-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - pal-network
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  user:
    image: lucagrandi/portfolio-pal:user
    container_name: user
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    networks:
      - pal-network
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
      - eureka.instance.prefer-ip-address=true

  asset:
    image: lucagrandi/portfolio-pal:asset
    container_name: asset
    ports:
      - 8080:8080
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - pal-network
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
      - eureka.instance.prefer-ip-address=true

  transactiondb:
    container_name: transactiondb
    image: "mariadb"
    networks:
      - transaction-network
      - pal-network
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: transaction
      MARIADB_PASSWORD: transaction
      MARIADB_DATABASE: transaction
      TZ: Europe/Rome
    restart: always
    volumes:
      - type: volume
        source: transaction-data
        target: /data
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  transaction:
    image: lucagrandi/portfolio-pal:transaction
    container_name: transaction
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      transactiondb:
        condition: service_healthy
      service-discovery:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://transactiondb:3306/transaction?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=transaction
      - SPRING_DATASOURCE_PASSWORD=transaction
      - SPRING_RABBITMQ_HOST=rabbitmq
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    networks:
      - transaction-network
      - pal-network

  historydb:
    container_name: historydb
    image: "mariadb"
    networks:
      - history-network
      - pal-network
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: history
      MARIADB_PASSWORD: history
      MARIADB_DATABASE: history
      TZ: Europe/Rome
    restart: always
    volumes:
      - type: volume
        source: history-data
        target: /data
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  portfolio-history:
    image: lucagrandi/portfolio-pal:history
    container_name: portfolio-history
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://historydb:3306/history?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=history
      - SPRING_DATASOURCE_PASSWORD=history
      - SPRING_RABBITMQ_HOST=rabbitmq
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    networks:
      - history-network
      - pal-network
    depends_on:
      service-discovery:
        condition: service_healthy
      historydb:
        condition: service_healthy
      transaction:
        condition: service_started
      asset:
        condition: service_started

  api-gateway:
    image: lucagrandi/portfolio-pal:api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
      - eureka.instance.prefer-ip-address=true
    depends_on:
      service-discovery:
        condition: service_healthy
      user:
        condition: service_started
      asset:
        condition: service_started
      portfolio-history:
        condition: service_started
      transaction:
        condition: service_started
    networks:
      - pal-network
    restart: always

  web-app:
    image: lucagrandi/portfolio-pal:web-app
    container_name: web-app
    ports:
      - 4201:4200
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - pal-network

volumes:
  history-data:
  transaction-data:

networks:
  transaction-network:
  history-network:
  pal-network:
