services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      transactiondb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://transactiondb:3306/transaction?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=transaction
      - SPRING_DATASOURCE_PASSWORD=transaction
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - transaction-network
      - pal-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - pal-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  transactiondb:
    container_name: transactiondb
    image: "mariadb"
    networks:
      - transaction-network
      - pal-network
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: transaction
      MARIADB_PASSWORD: transaction
      MARIADB_DATABASE: transaction
      TZ: Europe/Rome
    restart: unless-stopped
    volumes:
      - type: volume
        source: transaction-data
        target: /data
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  transaction-data:
networks:
  transaction-network:
    name: transaction-network
  pal-network:
    name: pal-network
    driver: bridge
