# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Clean Install in 'asset' directory
      run: |
        cd asset
        mvn clean install
    - name: Check code coverage for 'asset'
      run: |
        cd asset
        COVERAGE=$(mvn jacoco:report | grep -Po '(?<=<counter type="INSTRUCTION" missed=".*" covered=").*?(?=")')
        THRESHOLD=60
        if (( $(echo "$COVERAGE < $THRESHOLD" |bc -l) )); then
          echo "Code coverage for 'asset' ($COVERAGE%) is below the acceptable threshold ($THRESHOLD%)"
          exit 1
        else
          echo "Code coverage for 'asset' is sufficient: $COVERAGE%"
        fi
    # - name: Run Clean Install in 'transaction' directory
    #   run: |
    #     cd transaction
    #     mvn clean install
